### ISSUE TITLE
[SR2022]: 2022-01-28 Meet the team - Tom Wheal

### ISSUE THREAD

**Issue by antoinepetty** [srobo/social-media-posts#10]
### Body

In this new blog series we meet Tom, who is now an Electronics Consultant. Tom competed in SR2014 and SR2015 as a part of team PSC from @Symonds_College and is now a volunteer.

Find out more about his journey:
https://studentrobotics.org/blog/2022-01-24-meet-the-team-tom-wheal/

#srobo #stem #robotics

**Comment by antoinepetty** [comment]
![image](https://user-images.githubusercontent.com/36314396/151448088-613c8949-4481-4b70-889f-52eceb88c7f9.png)

**Comment by sedders123** [comment]
https://twitter.com/studentrobotics/status/1487017612215263240
