### ISSUE TITLE
[SR2022]: 2022-02-03 Competition date announcement

### ISSUE THREAD

**Issue by antoinepetty** [srobo/social-media-posts#11]
### Body

todo

### Category

Current Comp Cycle News

**Comment by JS12345678910** [comment]
![Srobo Comp announcment ](https://user-images.githubusercontent.com/98554844/151446215-e821435b-16bd-4201-b7b7-b32ecc39dd57.png)

**Comment by JS12345678910** [comment]
Lets get ready to robot! The official dates for our competition are out now. #srobo #stem #srobo2022 #robotics 

For more information: https://studentrobotics.org/blog/2022-02-03-competition-date-announced/

**Comment by antoinepetty** [comment]
Replaced event link with blog link
