### ISSUE TITLE
[SR2022]: 2022-02-18 Adventurous Machines Sponsored Post

### ISSUE THREAD

**Issue by antoinepetty** [srobo/social-media-posts#13]
### Body

A huge thank you to our sponsor Adventurous Machines. Adventurous Machines offers a bespoke electronic design service and takes products from concept to reality. Their support helps us inspire the next generation of engineers! Find out more at https://adventurousmachines.com/?utm_source=twitter&utm_campaign=sr2022

### Media

Logo on SR grey background

### Category

Current Comp Cycle News

**Comment by sedders123** [comment]
Posted Yesterday
