### ISSUE TITLE
[SR2022]: 2022-03-23 1 Month to go

### ISSUE THREAD

**Issue by sedders123** [srobo/social-media-posts#15]
### Body

With just 50 days to go, teams are working hard to finish their robots. Be sure to join us for the epic conclusion to this year's competition!

#srobo #srobo2022 #stem #robotics

### Media

https://drive.google.com/file/d/1zczR2ivgV9dV01V5MlaAtI-GEjQwnYgM/view?usp=sharing

### Category

Current Comp Cycle News

**Comment by antoinepetty** [comment]
Changed and scheduled

**Comment by antoinepetty** [comment]
posted
